Convert mouse clicks to driver calls
iis-powp-2021z/powp_jobs2d_projects pull request #2
Opened 2021-12-21 16:58 UTC by MatBebenek

Clicking the mouse on the drawing panel results in drawing a line or moving the position of a device head.

2021-12-22 08:17 UTC, kowallus commented
Is it finished? Update trello board please.

2021-12-22 08:37 UTC, MatBebenek commented
Trello updated. Waiting for review

https://trello.com/c/voR76Nx9

2021-12-22 18:28 UTC, kowallus requested changes
The code quality is ok. I have some minor suggestions and issues to fix.

2021-12-22 18:28 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/events/SelectClearPanelOptionListener.java
> +    JPanel panel = DrawerFeature.getPanel();
You have wrong code convention (change to tabs!)

2021-12-22 18:28 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/SelectMouseFigureOptionListener.java
> +                driverManager.getCurrentDriver().setPosition(previousHeadXPosition, previousHeadYPosition);
Please, make rightClick modify only position so only leftClick would actually draw.

2021-12-22 18:28 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/SelectMouseFigureOptionListener.java
> +                    updatePreviousMousePosition(e, halfWindowWidth, halfWindowHeight);
Maybe the first click should always only do SetPosition?

2021-12-23 10:27 UTC, MatBebenek commented
MR was updated as requested in comments.

2021-12-29 18:10 UTC, merged

2021-12-29 18:10 UTC, kowallus commented
OK! You can claim a new task.